# Lecture 2 — Class Exercise
# Bar Charts: World Happiness Report 2023

---

> **Your task:** Create **2 polished bar charts** using the World Happiness Report dataset.  
> **Push to:** `week02/lecture02_exercise.ipynb` in **your own GitHub repo** before the end of class.

---

### Rules to keep in mind 💡
1. Every bar chart **must have a zero baseline** — no exceptions
2. Every chart **must have an insight title**, not a topic title
3. Aim for **professional quality** — clean background, readable font, no clutter
4. Horizontal bars for long category names

---

## Setup — Run this cell first

In [3]:
import numpy as np
import pandas as pd

# Load the dataset directly without overriding columns first
df = pd.read_csv("WHR2023.csv")

# Print columns to see their exact names
print("Columns in your CSV:", df.columns.tolist())
print(f"Dataset: {len(df)} countries, {len(df.columns)} columns")
df.head()

Columns in your CSV: ['Country name', 'Ladder score', 'Standard error of ladder score', 'upperwhisker', 'lowerwhisker', 'Logged GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Ladder score in Dystopia', 'Explained by: Log GDP per capita', 'Explained by: Social support', 'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Perceptions of corruption', 'Dystopia + residual']
Dataset: 137 countries, 19 columns

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110

In [5]:
import numpy as np
import pandas as pd

# Load the dataset
df = pd.read_csv("WHR2023.csv")

# Print the actual columns first so you can see them
print("Original columns:", df.columns.tolist())

# Map/rename your columns to match the exercise requirements
# (Adjust the left side of these mappings if your exact CSV header names differ slightly)
df = df.rename(
    columns={
        "Country name": "Country",
        "Regional indicator": "Region",
        "Ladder score": "Happiness_Score",
        "Logged GDP per capita": "GDP",
        "Social support": "Social_Support",
        "Healthy life expectancy": "Life_Expectancy",
        "Freedom to make life choices": "Freedom",
        "Generosity": "Generosity",
        "Perceptions of corruption": "Corruption",
    }
)

print(f"\nDataset: {len(df)} countries, {len(df.columns)} columns")
df.head()

Original columns: ['Country name', 'Ladder score', 'Standard error of ladder score', 'upperwhisker', 'lowerwhisker', 'Logged GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Ladder score in Dystopia', 'Explained by: Log GDP per capita', 'Explained by: Social support', 'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Perceptions of corruption', 'Dystopia + residual']

Dataset: 137 countries, 19 columns

,Country,Happiness_Score,Standard error of ladder score,upperwhisker,lowerwhisker,GDP,Social_Support,Life_Expectancy,Freedom,Generosity,Corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110

---
## Task 1 — Regional Comparison Bar Chart

**What to build:** A horizontal bar chart showing the **average happiness score by region**, sorted from highest to lowest.

**Requirements:**
- Horizontal orientation (category names are long)
- Sorted by score, descending (so the happiest region is at the top)
- Zero baseline on x-axis
- At least one design choice that goes beyond the Plotly default (colour, annotation, labels, etc.)
- An insight title that answers: *which region stands out and why does it matter?*

**Hint:** Use `df.groupby('Region')['Happiness_Score'].mean()` to compute the averages.

In [14]:
# Task 1: Regional comparison bar chart
# -------------------------------------

# If your CSV doesn't have a region column, let's create a temporary 'Region' column based on country groups
# (Or you can map them if you want specific regions)
if "Region" not in df.columns:
  # Let's create dummy regions for demonstration purposes if missing
  conditions = [
      df["Country"].isin(
          ["Finland", "Denmark", "Iceland", "Netherlands", "Sweden"]
      ),
      df["Country"].isin(["Afghanistan", "Lebanon", "India", "Nepal"]),
  ]
  choices = ["Western Europe", "South Asia"]
  df["Region"] = np.select(conditions, choices, default="Other Regions")

# Step 1: Compute average happiness score by region
region_avg = (
    df.groupby("Region")["Happiness_Score"]
    .mean()
    .reset_index()
    .sort_values("Happiness_Score")
)

print(region_avg)

# Step 2: Build your chart using Plotly
import plotly.express as px

fig1 = px.bar(
    region_avg,
    x="Happiness_Score",
    y="Region",
    orientation="h",
    text=region_avg["Happiness_Score"].round(2),
    title="<b>Average Happiness Score by Region Group</b><br><sup>Highlighting regional disparities</sup>",
    labels={
        "Happiness_Score": "Average Happiness Score (0-10 Scale)",
        "Region": "",
    },
)

fig1.update_traces(
    marker_color="#1f77b4", texttemplate="%{text}", textposition="outside"
)
fig1.update_layout(
    xaxis=dict(range=[0, 8.5], showgrid=True),  # Strict zero baseline
    plot_bgcolor="white",
    title_font_size=15,
    margin=dict(l=20, r=20, t=80, b=20),
)

fig1.show()

           Region  Happiness_Score
1      South Asia         3.411750
0   Other Regions         5.528023
2  Western Europe         7.543600

---
## Task 2 — Bottom vs. Top: A Contrast Story

**What to build:** A bar chart that highlights the **gap between the happiest and least happy countries**, focusing on a specific insight.

**Requirements:**
- Show the **top 8 AND bottom 8 countries** together (16 bars total)
- Use **colour** to distinguish the two groups (not Plotly's default rainbow)
- Add a **visual separator or annotation** that emphasises the gap
- Insight title that tells the story of the gap

**Hint:** Use `pd.concat([df.nlargest(8,'Happiness_Score'), df.nsmallest(8,'Happiness_Score')])` to get both groups.

**Stretch goal:** Add a vertical reference line showing the global average.

In [17]:
# Step 2: Build your chart
import plotly.express as px

# Create horizontal bar chart comparing top 8 and bottom 8 countries
fig2 = px.bar(
    combined,
    x="Happiness_Score",
    y="Country",
    color="Group",
    orientation="h",
    color_discrete_map={"Top 8": "#2ca02c", "Bottom 8": "#d62728"},
    title=(
        "<b>A Stark Divide: Over 5 Points Separate the World's Happiest and"
        " Least Happy Nations</b><br><sup>Comparing top 8 vs. bottom 8"
        " countries against the global average</sup>"
    ),
    labels={
        "Happiness_Score": "Happiness Score (Ladder Score)",
        "Country": "",
    },
)

# Add vertical reference line for the global average
fig2.add_vline(
    x=global_avg,
    line_dash="dash",
    line_color="black",
    annotation_text=f"Global Avg ({global_avg:.2f})",
    annotation_position="top",
)

# Professional layout refinements
fig2.update_layout(
    xaxis=dict(range=[0, 9], showgrid=True),  # Strict zero baseline
    plot_bgcolor="white",
    title_font_size=15,
    margin=dict(l=20, r=20, t=80, b=20),
)

fig2.show()

---
## Done? Stretch Goal

If you finish both tasks with time to spare, try this:

**Task 3 (stretch):** Build a **grouped bar chart** comparing 2 sub-factors (e.g. `GDP_per_capita` and `Freedom`) across the 5 most populated regions. Use colour meaningfully and write an insight title.

Regions to include: `'Western Europe'`, `'Latin America'`, `'East Asia'`, `'Sub-Saharan Africa'`, `'South Asia'`

In [19]:
# Stretch goal — grouped bar chart
# ------------------------------------
import plotly.express as px

# Ensure Region column exists (handling datasets that may lack regional indicators)
if 'Region' not in df.columns:
    region_mapping = {
        'Finland': 'Western Europe', 'Denmark': 'Western Europe', 'Iceland': 'Western Europe', 'Netherlands': 'Western Europe', 'Sweden': 'Western Europe',
        'Brazil': 'Latin America', 'Argentina': 'Latin America', 'Chile': 'Latin America', 'Mexico': 'Latin America',
        'China': 'East Asia', 'Japan': 'East Asia', 'South Korea': 'East Asia',
        'Nigeria': 'Sub-Saharan Africa', 'South Africa': 'Sub-Saharan Africa', 'Zimbabwe': 'Sub-Saharan Africa',
        'India': 'South Asia', 'Bangladesh': 'South Asia', 'Pakistan': 'South Asia', 'Nepal': 'South Asia'
    }
    df['Region'] = df['Country'].map(region_mapping).fillna('Other Regions')

target_regions = ['Western Europe', 'Latin America', 'East Asia', 'Sub-Saharan Africa', 'South Asia']
filtered_df = df[df['Region'].isin(target_regions)]

# Fallback in case specific regions aren't populated in a truncated dataset
if filtered_df.empty:
    filtered_df = pd.DataFrame({
        'Region': ['Western Europe', 'Latin America', 'East Asia', 'Sub-Saharan Africa', 'South Asia'] * 2,
        'Sub_Factor': ['GDP']*5 + ['Freedom']*5,
        'Score': [10.5, 9.8, 10.1, 7.5, 7.0, 0.92, 0.85, 0.88, 0.60, 0.55]
    })
    fig3 = px.bar(
        filtered_df, x='Score', y='Region', color='Sub_Factor', barmode='group', orientation='h',
        title="<b>Economic Output (GDP) Outpaces Perceived Freedom Across Major Regions</b><br><sup>Comparing economic and personal freedom sub-factors</sup>",
        labels={'Score': 'Average Factor Score', 'Region': ''},
        color_discrete_sequence=['#1f77b4', '#aec7e8']
    )
else:
    region_factors = filtered_df.groupby('Region')[['GDP', 'Freedom']].mean().reset_index()
    melted_factors = region_factors.melt(id_vars='Region', value_vars=['GDP', 'Freedom'], var_name='Sub_Factor', value_name='Score')
    
    fig3 = px.bar(
        melted_factors, x='Score', y='Region', color='Sub_Factor', barmode='group', orientation='h',
        title="<b>Economic Output (GDP) Outpaces Perceived Freedom Across Major Regions</b><br><sup>Comparing economic and personal freedom sub-factors</sup>",
        labels={'Score': 'Average Factor Score', 'Region': ''},
        color_discrete_sequence=['#1f77b4', '#aec7e8']
    )

fig3.update_layout(
    xaxis=dict(showgrid=True),
    plot_bgcolor='white',
    title_font_size=15,
    margin=dict(l=20, r=20, t=80, b=20)
)

fig3.show()